// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Workflow.Api.Infrastructure.Data;

namespace Workflow.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(WorkContext))]
    [Migration("20221027055924_init-migration")]
    partial class initmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Workflow.Api.Models.Entities.WorkflowCaseInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("WorkflowDefinitionId")
                        .HasColumnType("longtext");

                    b.Property<string>("WorkflowInstanceId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("workflow_case_instance");
                });
#pragma warning restore 612, 618
        }
    }
}
