// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Workflow.Api.Infrastructure.Data;

namespace Workflow.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(WorkContext))]
    partial class WorkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Workflow.Api.Models.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("CaseChannelId")
                        .HasColumnType("int")
                        .HasColumnName("case_channel_id");

                    b.Property<int?>("CaseMainTypeId")
                        .HasColumnType("int")
                        .HasColumnName("case_main_type_id");

                    b.Property<string>("CaseMainTypeName")
                        .HasColumnType("longtext")
                        .HasColumnName("case_main_type_name");

                    b.Property<int?>("CaseSourceId")
                        .HasColumnType("int")
                        .HasColumnName("case_source_id");

                    b.Property<string>("CaseSourceName")
                        .HasColumnType("longtext")
                        .HasColumnName("case_source_name");

                    b.Property<int?>("CaseSubTypeId")
                        .HasColumnType("int")
                        .HasColumnName("case_sub_type_id");

                    b.Property<string>("CaseSubTypeName")
                        .HasColumnType("longtext")
                        .HasColumnName("case_sub_type_name");

                    b.Property<int?>("CaseTypeId")
                        .HasColumnType("int")
                        .HasColumnName("case_type_id");

                    b.Property<string>("CaseTypeName")
                        .HasColumnType("longtext")
                        .HasColumnName("case_type_name");

                    b.Property<string>("Code")
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<int?>("CommunityId")
                        .HasColumnType("int")
                        .HasColumnName("community_id");

                    b.Property<string>("CommunityName")
                        .HasColumnType("longtext")
                        .HasColumnName("community_name");

                    b.Property<int?>("StreetId")
                        .HasColumnType("int")
                        .HasColumnName("street_id");

                    b.Property<string>("StreetName")
                        .HasColumnType("longtext")
                        .HasColumnName("street_name");

                    b.HasKey("Id");

                    b.ToTable("case");
                });

            modelBuilder.Entity("Workflow.Api.Models.Entities.WorkflowActivityInstanceUser", b =>
                {
                    b.Property<string>("WorkflowActivityInstanceId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WorkflowActivityInstanceId", "UserId");

                    b.ToTable("workflow_activity_instance_user");
                });

            modelBuilder.Entity("Workflow.Api.Models.Entities.WorkflowCaseInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("WorkflowDefinitionId")
                        .HasColumnType("longtext");

                    b.Property<string>("WorkflowInstanceId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("workflow_case_instance");
                });
#pragma warning restore 612, 618
        }
    }
}
